name: cardano_wallet_sdk
description: Targeting Flutter apps, the Cardano Wallet SDK is a high-level Dart library for managing cryptocurrency accounts & executing transactions on the blockchain.
version: 0.1.0-alpha.8
homepage: https://github.com/reaster/cardano_wallet_sdk

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  blockfrost: ^1.0.0-dev.8
  bip32_ed25519: ^0.2.1
  pinenacl: ^0.3.3
  bip39: ^1.0.6
  cbor: ^4.1.0
  dio: ^4.0.3
  convert: ^3.0.0
  collection: ^1.15.0
  intl: ^0.17.0
  typed_data: ^1.3.0
  built_collection: ^5.1.0
  built_value: ^8.1.0
  hex: ^0.2.0
  quiver: ^3.0.1+1
  oxidized: ^5.1.0  #TODO swap oxidized Result for dartz Either?
  coingecko_dart: ^0.1.0  #TODO remove coingecko_dart

dev_dependencies:
  test: any
  mockito: ^5.0.10
  build_runner: ^2.1.5
  lints: ^1.0.1
  http: ^0.13.4

dependency_overrides:
  #  blockfrost:
    # git: git@github.com:reaster/blockfrost_api.git
    # path: ../blockfrost_api
